############################# Filebeat #####################################
filebeat:
  prospectors:
    -
      paths:
        - /var/log/workers.log
      fields:
        logzio_codec: json
        token: ${LOGZIO_API_TOKEN}
        type: server
      fields_under_root: true
      encoding: utf-8
      ignore_older: 3h

  registry_file: /var/lib/filebeat/registry
############################# Output ##########################################
output:
  logstash:
    hosts: ["listener.logz.io:5015"]

#  The below configuration is used for Filebeat 1.3 or lower
    tls:
      certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']

#  The below configuration is used for Filebeat 5.0 or higher
    ssl:
      certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']
